# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
# liip_imagine:
#   driver: "gd"
#   filter_sets:
#     thumb:
#       quality: 75
#       filters:
#         thumbnail:
#           size: [360, 230]
#           mode: outbound
#     medium:
#       quality: 75
#       filters:
#         thumbnail:
#           size: [1800, 1530]
#           mode: outbound
#   twig:
#     mode: lazy
