security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    App\Entity\Employe: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username
    app_employe_provider:
      entity:
        class: App\Entity\Employe
        property: email
    all_users:
      chain:
        providers: ["app_user_provider", "app_employe_provider"]

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      logout:
        path: /logout
        target: /
      form_login:
        login_path: login
        check_path: login
        default_target_path: /admin
        provider: all_users

  # activate different ways to authenticate
  # https://symfony.com/doc/current/security.html#firewalls-authentication

  # https://symfony.com/doc/current/security/impersonating_user.html
  # switch_user: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_USER] }
    - { path: ^/profile, roles: ROLE_USER }
