accueil:
  path: "/"
  controller: 'App\Controller\AccueilController::index'

service:
  path: "/service"
  controller: 'App\Controller\ServiceController::index'

occasion:
  path: "/occasion"
  controller: 'App\Controller\OccasionController::index'

commentaires:
  path: "/commentaires"
  controller: 'App\Controller\CommentairesController::index'

detail:
  path: "/detail/{id}"
  controller: 'App\Controller\OccasionController::details'

index:
  path: "/admin"
  controller: 'App\Controller\Admin\AdminVoitureController::index'

edit:
  path: "/admin/voitures/edit/{id}"
  controller: 'App\Controller\Admin\AdminVoitureController::edit'

new:
  path: "/admin/voitures/new"
  controller: 'App\Controller\Admin\AdminVoitureController::new'

supprimer:
  path: "/supprimer/{id}"
  controller: 'App\Controller\Admin\AdminVoitureController::supprimer'
  methods: [DELETE]

login:
  path: /login
  controller: 'App\Controller\SecurityController::login'
  methods: [GET, POST]

logout:
  path: /logout

editEmploye:
  path: "/security/editEmploye/{id}"
  controller: 'App\Controller\EmployeController::editEmploye'

newEmploye:
  path: "/security/newEmploye"
  controller: 'App\Controller\EmployeController::newEmploye'

supprimerEmploye:
  path: "/security/supprimer_employe/{id}"
  controller: 'App\Controller\EmployeController::supprimerEmploye'
  methods: ["DELETE"]

editHoraire:
  path: "/admin/horaires/editHoraire/{id}"
  controller: 'App\Controller\Admin\AdminHoraireController::editHoraire'

newHoraire:
  path: "/admin/horaires/newHoraire"
  controller: 'App\Controller\Admin\AdminHoraireController::newHoraire'

supprimerHoraire:
  path: "/admin/horaires/supprimer_Horaire/{id}"
  controller: 'App\Controller\Admin\AdminHoraireController::supprimerHoraire'
  methods: ["DELETE"]

admin_horaires:
  path: "/admin/horaires"
  controller: 'App\Controller\Admin\AdminHoraireController::index'
