accueil:
  path: "/accueil"
  controller: 'App\Controller\AccueilController::index'
service:
  path: "/service"
  controller: 'App\Controller\ServiceController::index'
occasion:
  path: "/occasion"
  controller: 'App\Controller\OccasionController::index'
contact:
  path: "/contact"
  controller: 'App\Controller\ContactController::index'
detail:
  path: "/detail/{id}"
  controller: 'App\Controller\OccasionController::details'
