accueil:
  path: "/accueil"
  controller: 'App\Controller\AccueilController::index'
service:
  path: "/service"
  controller: 'App\Controller\ServiceController::index'
occasion:
  path: "/occasion"
  controller: 'App\Controller\OccasionController::index'
contact:
  path: "/contact"
  controller: 'App\Controller\ContactController::index'
detail:
  path: "/detail/{id}"
  controller: 'App\Controller\OccasionController::details'
index:
  path: "/admin/voitures/index"
  controller: 'App\Controller\Admin\AdminVoitureController::index'
edit:
  path: "/admin/voitures/edit/{id}"
  controller: 'App\Controller\Admin\AdminVoitureController::edit'
new:
  path: "/admin/voitures/new"
  controller: 'App\Controller\Admin\AdminVoitureController::new'
supprimer:
  path: "/supprimer/{id}"
  controller: 'App\Controller\Admin\AdminVoitureController::supprimer'
  methods: [DELETE]
